#!/usr/bin/env python3
# script that takes in the number of seconds and converts it to HH:MM:SS format

from sys import argv

remaining_seconds = int(argv[1])

hours = remaining_seconds // 3600
remaining_seconds -= 3600 * hours
minutes = remaining_seconds // 60
remaining_seconds -= 60 * minutes

if len(str(hours)) == 1:
    hours = '0' + str(hours)

if len(str(minutes)) == 1:
    minutes = '0' + str(minutes)

print(str(hours) + ':' + str(minutes) + ':' + str(remaining_seconds))
